# Generated by Django 5.2.6 on 2025-09-24 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_adotante'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='adotante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animais', to='core.adotante'),
        ),
    ]
