# Generated by Django 5.2.6 on 2025-09-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_animal_adotante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adotante',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
