# Generated by Django 5.2.7 on 2025-11-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_adotante_cpf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adotante',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['nome'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AlterModelOptions(
            name='consultaveterinaria',
            options={'ordering': ['-data']},
        ),
        migrations.AlterModelOptions(
            name='ong',
            options={'ordering': ['nome']},
        ),
    ]
