# Generated by Django 5.2.7 on 2025-11-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_adotante_options_alter_animal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaveterinaria',
            name='data',
            field=models.DateField(),
        ),
    ]
