# Generated by Django 5.2.7 on 2025-11-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_consultaveterinaria_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adotante',
            options={'ordering': ['nome'], 'verbose_name': 'Adotante', 'verbose_name_plural': 'Adotantes'},
        ),
        migrations.AlterModelOptions(
            name='consultaveterinaria',
            options={'ordering': ['-data'], 'verbose_name': 'Consulta Veterinária', 'verbose_name_plural': 'Consultas Veterinárias'},
        ),
        migrations.AlterModelOptions(
            name='ong',
            options={'ordering': ['nome'], 'verbose_name': 'ONG', 'verbose_name_plural': 'ONGs'},
        ),
        migrations.AlterField(
            model_name='adotante',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato'), ('outro', 'Outro')], default='cachorro', max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ong',
            name='contato',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
